// =============================================
//  STREAMVAULT – MOVIE DATABASE
//  Posters via TMDB image CDN (public URLs)
// =============================================

const ALL_MOVIES = [
  // ── 2024–2025 LATEST ──
  { id:1,  title:"Dune: Part Two",        year:2024, rating:8.5, genre:"Sci-Fi",    duration:"2h 46m", poster:"https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",  desc:"Paul Atreides unites with the Fremen on a journey of revenge against the conspirators who destroyed his family.", cast:"Timothée Chalamet, Zendaya, Rebecca Ferguson", type:"movie", trending:true,  award:false },
  { id:2,  title:"Inside Out 2",           year:2024, rating:7.9, genre:"Animation", duration:"1h 40m", poster:"https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",  desc:"Riley enters adolescence and new emotions move into Headquarters – including Anxiety, who very much has her own ideas.", cast:"Amy Poehler, Maya Hawke, Kensington Tallman", type:"movie", trending:true,  award:false },
  { id:3,  title:"Deadpool & Wolverine",   year:2024, rating:8.1, genre:"Action",   duration:"2h 8m",  poster:"https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",  desc:"Deadpool is offered a place in the Marvel Cinematic Universe but the deal requires bringing along an unwilling Wolverine.", cast:"Ryan Reynolds, Hugh Jackman", type:"movie", trending:true,  award:false },
  { id:4,  title:"Alien: Romulus",         year:2024, rating:7.4, genre:"Horror",   duration:"1h 59m", poster:"https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",  desc:"A group of young colonists face the most terrifying life form in the universe while scavenging an abandoned space station.", cast:"Cailee Spaeny, David Jonsson", type:"movie", trending:true,  award:false },
  { id:5,  title:"Twisters",               year:2024, rating:7.2, genre:"Action",   duration:"2h 3m",  poster:"https://image.tmdb.org/t/p/w500/pjnD08FlMAIXsfOLKQbovhFbOVC.jpg",  desc:"Kate Cooper is lured back to the open plains of Oklahoma when terrifying new storm patterns begin to form.", cast:"Daisy Edgar-Jones, Glen Powell", type:"movie", trending:false, award:false },
  { id:6,  title:"A Quiet Place: Day One", year:2024, rating:7.0, genre:"Horror",   duration:"1h 39m", poster:"https://image.tmdb.org/t/p/w500/yrpPYKijwdMHyTGIOd1iK1h0Tf6.jpg",  desc:"Experience the day the world went quiet in New York City as it is invaded by alien creatures.", cast:"Lupita Nyong'o, Joseph Quinn", type:"movie", trending:false, award:false },
  { id:7,  title:"Despicable Me 4",        year:2024, rating:6.8, genre:"Animation",duration:"1h 35m", poster:"https://image.tmdb.org/t/p/w500/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",  desc:"Gru and Lucy must deal with a new villain called Maxime Le Mal who threatens their family.", cast:"Steve Carell, Kristen Wiig", type:"movie", trending:false, award:false },
  { id:8,  title:"Furiosa",                year:2024, rating:7.8, genre:"Action",   duration:"2h 28m", poster:"https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",  desc:"The story of how the young Furiosa falls into the hands of a great Biker Horde and grows up to become a warrior.", cast:"Anya Taylor-Joy, Chris Hemsworth", type:"movie", trending:false, award:true  },
  { id:9,  title:"Kingdom of the Planet of the Apes", year:2024, rating:7.3, genre:"Sci-Fi", duration:"2h 25m", poster:"https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg", desc:"Many generations in the future following Caesar's reign, apes are the dominant species.", cast:"Owen Teague, Freya Allan", type:"movie", trending:true, award:false },
  { id:10, title:"Longlegs",               year:2024, rating:6.4, genre:"Thriller", duration:"1h 41m", poster:"https://image.tmdb.org/t/p/w500/nKNEE6eTnu2J76b3tR7a8fFOt72.jpg",  desc:"FBI Agent Lee Harker is assigned to an unsolved case of a serial killer who has left a strange connection to Satanism.", cast:"Maika Monroe, Nicolas Cage", type:"movie", trending:false, award:false },

  // ── 2023 HITS ──
  { id:11, title:"Oppenheimer",            year:2023, rating:8.9, genre:"Drama",    duration:"3h",     poster:"https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",  desc:"The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", cast:"Cillian Murphy, Emily Blunt, Matt Damon", type:"movie", trending:false, award:true  },
  { id:12, title:"Barbie",                 year:2023, rating:6.9, genre:"Comedy",   duration:"1h 54m", poster:"https://image.tmdb.org/t/p/w500/iuFNMS8vlbCFDUsx8q4lBzKbVhH.jpg",  desc:"Barbie suffers a crisis that leads her to question her world and her existence.", cast:"Margot Robbie, Ryan Gosling", type:"movie", trending:false, award:true  },
  { id:13, title:"Guardians of the Galaxy Vol. 3", year:2023, rating:7.9, genre:"Action", duration:"2h 30m", poster:"https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgood5an.jpg", desc:"Peter Quill still reeling from the loss of Gamora must rally his team around him to defend the universe.", cast:"Chris Pratt, Zoe Saldana, Bradley Cooper", type:"movie", trending:false, award:false },
  { id:14, title:"The Super Mario Bros. Movie", year:2023, rating:7.1, genre:"Animation", duration:"1h 32m", poster:"https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggkR.jpg", desc:"A plumber named Mario travels through an underground labyrinth with his brother Luigi to rescue a captured princess.", cast:"Chris Pratt, Anya Taylor-Joy, Charlie Day", type:"movie", trending:false, award:false },
  { id:15, title:"Killers of the Flower Moon", year:2023, rating:7.6, genre:"Drama", duration:"3h 26m", poster:"https://image.tmdb.org/t/p/w500/dB6Krk806zeqd955OR8ib0faizR.jpg", desc:"Members of the Osage Nation are murdered under mysterious circumstances in the 1920s, sparking a major FBI investigation.", cast:"Leonardo DiCaprio, Robert De Niro", type:"movie", trending:false, award:true  },
  { id:16, title:"Mission: Impossible – Dead Reckoning", year:2023, rating:7.7, genre:"Action", duration:"2h 43m", poster:"https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg", desc:"Ethan Hunt and his IMF team embark on their most dangerous mission yet: to track down a terrifying new weapon before it falls into the wrong hands.", cast:"Tom Cruise, Hayley Atwell", type:"movie", trending:false, award:false },
  { id:17, title:"Spider-Man: Across the Spider-Verse", year:2023, rating:8.6, genre:"Animation", duration:"2h 20m", poster:"https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", desc:"Miles Morales catapults across the multiverse where he encounters a team of Spider-People.", cast:"Shameik Moore, Hailee Steinfeld", type:"movie", trending:false, award:true  },
  { id:18, title:"John Wick: Chapter 4",   year:2023, rating:7.7, genre:"Action",   duration:"2h 49m", poster:"https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",  desc:"John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.", cast:"Keanu Reeves, Donnie Yen", type:"movie", trending:false, award:false },
  { id:19, title:"Elemental",              year:2023, rating:6.8, genre:"Animation",duration:"1h 41m", poster:"https://image.tmdb.org/t/p/w500/6oH378KUfgKMaXKeIs4LJ6ZF7fZ.jpg",  desc:"In a city where Fire, Water, Land and Air residents live together, a fiery young woman and a go-with-the-flow guy discover something elemental.", cast:"Leah Lewis, Mamoudou Athie", type:"movie", trending:false, award:false },
  { id:20, title:"Cocaine Bear",           year:2023, rating:6.0, genre:"Thriller", duration:"1h 35m", poster:"https://image.tmdb.org/t/p/w500/gOnmaxHo0412nbOPMfSo0pWoggH.jpg",  desc:"An oddball group of criminals, hikers and police officers converge on a Georgia forest where a 500-pound black bear has ingested cocaine.", cast:"Keri Russell, Ray Liotta", type:"movie", trending:false, award:false },

  // ── 2022 ──
  { id:21, title:"Top Gun: Maverick",      year:2022, rating:8.3, genre:"Action",   duration:"2h 11m", poster:"https://image.tmdb.org/t/p/w500/62HCnUTHOCOCM0BNLkFtHqjGdA2.jpg",  desc:"After more than thirty years of service, Pete 'Maverick' Mitchell is where he belongs, pushing the envelope as a courageous test pilot.", cast:"Tom Cruise, Miles Teller, Jennifer Connelly", type:"movie", trending:false, award:true  },
  { id:22, title:"Everything Everywhere All at Once", year:2022, rating:7.8, genre:"Sci-Fi", duration:"2h 19m", poster:"https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", desc:"A middle-aged Chinese immigrant is swept up in an insane adventure where she alone can save the world by exploring other universes.", cast:"Michelle Yeoh, Ke Huy Quan, Jamie Lee Curtis", type:"movie", trending:false, award:true  },
  { id:23, title:"Doctor Strange in the Multiverse of Madness", year:2022, rating:6.9, genre:"Action", duration:"2h 6m", poster:"https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg", desc:"Doctor Strange teams with a mysterious new ally who traverses the Multiverse under the guidance of her dreams.", cast:"Benedict Cumberbatch, Elizabeth Olsen", type:"movie", trending:false, award:false },
  { id:24, title:"The Batman",             year:2022, rating:7.8, genre:"Action",   duration:"2h 56m", poster:"https://image.tmdb.org/t/p/w500/74xTpMgo91K1oMSFq6VGRVxGhB5.jpg",  desc:"When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption.", cast:"Robert Pattinson, Zoë Kravitz", type:"movie", trending:false, award:false },
  { id:25, title:"Thor: Love and Thunder",  year:2022, rating:6.3, genre:"Action",  duration:"1h 59m", poster:"https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",  desc:"Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher.", cast:"Chris Hemsworth, Natalie Portman", type:"movie", trending:false, award:false },

  // ── 2021 ──
  { id:26, title:"No Time to Die",         year:2021, rating:7.3, genre:"Action",   duration:"2h 43m", poster:"https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FE6Du.jpg",   desc:"James Bond has left active service. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help.", cast:"Daniel Craig, Rami Malek, Ana de Armas", type:"movie", trending:false, award:false },
  { id:27, title:"Spider-Man: No Way Home", year:2021, rating:8.2, genre:"Action",  duration:"2h 28m", poster:"https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",  desc:"With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.", cast:"Tom Holland, Zendaya, Benedict Cumberbatch", type:"movie", trending:false, award:false },
  { id:28, title:"Dune: Part One",          year:2021, rating:8.0, genre:"Sci-Fi",  duration:"2h 35m", poster:"https://image.tmdb.org/t/p/w500/d5NXSklpcvkDkqEPqbp7E3ZOTeV.jpg",   desc:"Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe.", cast:"Timothée Chalamet, Rebecca Ferguson, Oscar Isaac", type:"movie", trending:false, award:true  },
  { id:29, title:"Black Widow",             year:2021, rating:6.8, genre:"Action",  duration:"2h 14m", poster:"https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO0z9Lj0M7GSIGE.jpg",  desc:"Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.", cast:"Scarlett Johansson, Florence Pugh", type:"movie", trending:false, award:false },
  { id:30, title:"Free Guy",                year:2021, rating:7.1, genre:"Comedy",  duration:"1h 55m", poster:"https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",  desc:"A bank teller discovers he is actually a background player in an open-world video game and decides to become the hero of his own story.", cast:"Ryan Reynolds, Jodie Comer", type:"movie", trending:false, award:false },

  // ── 2020 ──
  { id:31, title:"Tenet",                   year:2020, rating:7.3, genre:"Sci-Fi",  duration:"2h 30m", poster:"https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijZcpb.jpg",  desc:"Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.", cast:"John David Washington, Robert Pattinson", type:"movie", trending:false, award:false },
  { id:32, title:"Soul",                    year:2020, rating:8.0, genre:"Animation",duration:"1h 40m",poster:"https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",  desc:"A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an unborn soul.", cast:"Jamie Foxx, Tina Fey", type:"movie", trending:false, award:true  },
  { id:33, title:"Bad Boys for Life",       year:2020, rating:7.2, genre:"Action",   duration:"2h 4m", poster:"https://image.tmdb.org/t/p/w500/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",  desc:"Miami detectives Mike Lowrey and Marcus Burnett must face a blind threat from the past.", cast:"Will Smith, Martin Lawrence", type:"movie", trending:false, award:false },

  // ── CLASSIC & ALL-TIME GREAT ──
  { id:34, title:"Avengers: Endgame",       year:2019, rating:8.4, genre:"Action",   duration:"3h 1m", poster:"https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",  desc:"After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.", cast:"Robert Downey Jr., Chris Evans, Scarlett Johansson", type:"movie", trending:false, award:false },
  { id:35, title:"Joker",                   year:2019, rating:8.4, genre:"Drama",    duration:"2h 2m", poster:"https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",  desc:"A failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.", cast:"Joaquin Phoenix, Robert De Niro", type:"movie", trending:false, award:true  },
  { id:36, title:"Parasite",                year:2019, rating:8.5, genre:"Thriller", duration:"2h 12m",poster:"https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",  desc:"Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", cast:"Song Kang-ho, Lee Sun-kyun", type:"movie", trending:false, award:true  },
  { id:37, title:"Once Upon a Time in Hollywood", year:2019, rating:7.6, genre:"Drama", duration:"2h 41m", poster:"https://image.tmdb.org/t/p/w500/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg", desc:"A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age.", cast:"Leonardo DiCaprio, Brad Pitt", type:"movie", trending:false, award:false },
  { id:38, title:"The Lion King",           year:2019, rating:7.0, genre:"Animation",duration:"1h 58m",poster:"https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",  desc:"After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.", cast:"Donald Glover, Beyoncé, Chiwetel Ejiofor", type:"movie", trending:false, award:false },
  { id:39, title:"1917",                    year:2019, rating:8.2, genre:"Drama",    duration:"1h 59m",poster:"https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYQLv2vBmU.jpg",  desc:"Two British soldiers must cross enemy territory and deliver a message that will stop 1,600 men from walking into a deadly trap.", cast:"George MacKay, Dean-Charles Chapman", type:"movie", trending:false, award:true  },
  { id:40, title:"Knives Out",              year:2019, rating:7.9, genre:"Thriller", duration:"2h 10m",poster:"https://image.tmdb.org/t/p/w500/pThyQovXQrws2Q2iVEGjTeHQhWi.jpg",  desc:"A detective investigates the death of a crime novelist at his estate after his 85th birthday party.", cast:"Daniel Craig, Chris Evans, Ana de Armas", type:"movie", trending:false, award:false },

  // ── MORE 2024 ──
  { id:41, title:"Godzilla x Kong: The New Empire", year:2024, rating:6.3, genre:"Action", duration:"1h 55m", poster:"https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg", desc:"Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins.", cast:"Rebecca Hall, Brian Tyree Henry", type:"movie", trending:true, award:false },
  { id:42, title:"Civil War",               year:2024, rating:7.2, genre:"Thriller", duration:"1h 49m",poster:"https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",  desc:"A team of journalists race to reach Washington, D.C. during a second American Civil War before rebel forces close in.", cast:"Kirsten Dunst, Wagner Moura", type:"movie", trending:false, award:false },
  { id:43, title:"The Substance",           year:2024, rating:7.3, genre:"Horror",   duration:"2h 21m",poster:"https://image.tmdb.org/t/p/w500/lqoMzCcZYEFK729d6qzt349fB4o.jpg",  desc:"A fading celebrity dares to try a black market drug: a cell-replicating substance that will create a perfect, younger version of herself.", cast:"Demi Moore, Margaret Qualley", type:"movie", trending:true, award:true  },
  { id:44, title:"Challengers",             year:2024, rating:7.4, genre:"Drama",    duration:"2h 11m",poster:"https://image.tmdb.org/t/p/w500/H6vke7zGiuLinAQMRGKPqRHJnJF.jpg",  desc:"A tennis coach turned pro, his wife, and his former best friend must navigate a complicated and contentious relationship.", cast:"Zendaya, Josh O'Connor, Mike Faist", type:"movie", trending:false, award:false },
  { id:45, title:"Trap",                    year:2024, rating:6.8, genre:"Thriller", duration:"1h 45m",poster:"https://image.tmdb.org/t/p/w500/3slHOQJKbZJsqjjCgdWa7i3S5gQ.jpg",  desc:"A father and his teenage daughter attend a pop concert, where he slowly realizes the show is a large-scale police trap to catch a serial killer.", cast:"Josh Hartnett, Ariel Donoghue", type:"movie", trending:false, award:false },

  // ── TV SERIES ──
  { id:101, title:"House of the Dragon", year:2024, rating:8.4, genre:"Drama",   duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg", desc:"An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.", cast:"Paddy Considine, Emma D'Arcy, Matt Smith", type:"series", trending:true,  award:true  },
  { id:102, title:"The Bear",           year:2024, rating:8.8, genre:"Drama",   duration:"30m/ep", poster:"https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuB.jpg", desc:"A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.", cast:"Jeremy Allen White, Ayo Edebiri", type:"series", trending:true,  award:true  },
  { id:103, title:"Shogun",             year:2024, rating:8.6, genre:"Drama",   duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSXhopuUPWk9JkEi.jpg", desc:"John Blackthorne, an Elizabethan-era English navigator, finds himself lost in feudal Japan and must navigate treacherous samurai society.", cast:"Hiroyuki Sanada, Cosmo Jarvis", type:"series", trending:true,  award:true  },
  { id:104, title:"Fallout",            year:2024, rating:8.5, genre:"Sci-Fi",  duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/AnsSKR0TmJTMnkjWMnxLhNXM0Oo.jpg", desc:"Set in the universe of the classic video game series, the world 200 years after a nuclear apocalypse.", cast:"Ella Purnell, Walton Goggins", type:"series", trending:true,  award:false },
  { id:105, title:"The Penguin",        year:2024, rating:8.3, genre:"Action",  duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/f9vAzCHmjNQHiEXiQRDhCNbO1Y4.jpg", desc:"Oz Cobb — also known as the Penguin — fights to seize control of Gotham's criminal underworld after the death of Carmine Falcone.", cast:"Colin Farrell, Cristin Milioti", type:"series", trending:true,  award:false },
  { id:106, title:"Stranger Things S5", year:2025, rating:9.0, genre:"Sci-Fi",  duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", desc:"The fifth and final season brings the battle against the Upside Down to its epic conclusion.", cast:"Millie Bobby Brown, Finn Wolfhard, Winona Ryder", type:"series", trending:true, award:false },
  { id:107, title:"The Last of Us S2", year:2025, rating:9.1, genre:"Drama",   duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg", desc:"Joel and Ellie continue their journey in a post-apocalyptic world. Based on the critically acclaimed video game.", cast:"Pedro Pascal, Bella Ramsey, Kaitlyn Dever", type:"series", trending:true, award:true  },
  { id:108, title:"Severance",          year:2024, rating:8.7, genre:"Thriller","duration":"60m/ep",poster:"https://image.tmdb.org/t/p/w500/fzj6U1PNxmXSMW0pR3KBPgSfPaO.jpg", desc:"Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.", cast:"Adam Scott, Patricia Arquette, John Turturro", type:"series", trending:true,  award:true  },
  { id:109, title:"Slow Horses",        year:2024, rating:8.3, genre:"Thriller","duration":"60m/ep",poster:"https://image.tmdb.org/t/p/w500/k2vg8bYFRlTqWpxEMVZxkfbgLwG.jpg", desc:"A dysfunctional team of MI5 agents who serve as a dumping ground for members who've made career-ending mistakes.", cast:"Gary Oldman, Kristin Scott Thomas", type:"series", trending:false, award:false },
  { id:110, title:"The Boys",           year:2024, rating:8.7, genre:"Action",  duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg", desc:"A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.", cast:"Karl Urban, Jack Quaid, Antony Starr", type:"series", trending:false, award:false },
  { id:111, title:"Abbott Elementary",  year:2024, rating:8.2, genre:"Comedy",  duration:"30m/ep", poster:"https://image.tmdb.org/t/p/w500/veFmFpg5dDqRaKQItA3qUfHgWLp.jpg", desc:"A group of dedicated, passionate teachers (and a slightly delusional principal) navigate the daily ups and downs of running an under-resourced Philadelphia public school.", cast:"Quinta Brunson, Tyler James Williams", type:"series", trending:false, award:true  },
  { id:112, title:"Yellowjackets",      year:2024, rating:7.8, genre:"Horror",  duration:"60m/ep", poster:"https://image.tmdb.org/t/p/w500/qhGnGHmPTDdxgXZMxeAjdH7gYnI.jpg", desc:"What started as a survival tale reckons with the past as a group of high school girls-turned-adults try to keep dark secrets buried.", cast:"Melanie Lynskey, Christina Ricci", type:"series", trending:false, award:false },
];

// HERO MOVIES (featured banner rotation)
const HERO_MOVIES = [
  { id:1,  title:"Dune: Part Two",   bg:"https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", rating:8.5, year:2024, duration:"2h 46m", genre:"Sci-Fi",  desc:"Paul Atreides unites with the Fremen on a journey of revenge against the conspirators who destroyed his family." },
  { id:11, title:"Oppenheimer",      bg:"https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg", rating:8.9, year:2023, duration:"3h",    genre:"Drama",   desc:"The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb." },
  { id:107,title:"The Last of Us S2",bg:"https://image.tmdb.org/t/p/original/nWp7J8OBVVHRgwSjjgvqKYVrPuJ.jpg", rating:9.1, year:2025, duration:"60m/ep",genre:"Drama",   desc:"Joel and Ellie continue their journey in a post-apocalyptic world in this critically acclaimed HBO series." },
  { id:3,  title:"Deadpool & Wolverine", bg:"https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg", rating:8.1, year:2024, duration:"2h 8m", genre:"Action", desc:"Deadpool and an unwilling Wolverine team up in the most unexpected Marvel crossover event." },
];
